/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.edu.imepac.clinica.medica.medicos;

import br.edu.imepac.clinica.medica.daos.EspecialidadeDao;
import br.edu.imepac.clinica.medica.daos.MedicoDao;
import br.edu.imepac.clinica.medica.entidades.Especialidade;
import br.edu.imepac.clinica.medica.entidades.Medico;

import javax.swing.*;
import java.util.List;

/**
 * @author ehf_v
 */
public class AtualizarMedico extends javax.swing.JFrame {

    private EspecialidadeDao especialidadeDao;
    private MedicoDao medicoDao;

    /**
     * Creates new form CadastroEspecialidade
     */
    public AtualizarMedico(int id) {
        initComponents();
        inicializarEpecialidadeDao();
        inicializarMedicoDao();
        carregarEspecialidades();
        carregarDadosDeEdicao(id);
    }

    private void carregarDadosDeEdicao(int id) {
        try {
            Medico medico = medicoDao.buscarPorId(id);
            if (medico != null) {
                nomeText.setText(medico.getNome());
                crmText.setText(medico.getCrm());
                Especialidade especialidade = especialidadeDao.buscarPorId(medico.getEspecialidadeId());
                especialidadeJcombobox.setSelectedItem(especialidade);
            } else {
                JOptionPane.showMessageDialog(null, "Médico não encontrado!");
                dispose();
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Erro ao carregar dados do médico: " + e.getMessage());
            dispose();
        }
    }

    private void inicializarEpecialidadeDao() {
        try {
            this.especialidadeDao = new EspecialidadeDao();
        } catch (Exception exception) {
            JOptionPane.showMessageDialog(null, "Erro ao conectar ao banco de dados - especialidades!");
            dispose();
        }
    }

    private void inicializarMedicoDao() {
        try {
            this.medicoDao = new MedicoDao();
        } catch (Exception exception) {
            JOptionPane.showMessageDialog(null, "Erro ao inicializar ao banco de dados - médico!");
            dispose();
        }
    }

    private void carregarEspecialidades() {
        try {
            List<Especialidade> especialidadesList = especialidadeDao.listarTodas();
            if (especialidadesList.isEmpty()) {
                JOptionPane.showMessageDialog(null, "Nenhuma especialidade cadastrada! Cadastre uma especialidade antes de cadastrar um médico.");
                dispose();
                return;
            }
            especialidadesList.forEach(especialidade -> {
                this.especialidadeJcombobox.addItem(especialidade);
            });
        } catch (Exception exception) {
            JOptionPane.showMessageDialog(null, "Erro ao buscar especialidades!");
            dispose();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        nomeText = new javax.swing.JTextField();
        salvarJbutton = new javax.swing.JButton();
        fecharJbutton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        crmText = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        especialidadeJcombobox = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Nome");

        salvarJbutton.setText("Salvar");
        salvarJbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salvarJbuttonActionPerformed(evt);
            }
        });

        fecharJbutton.setText("Fechar");
        fecharJbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fecharJbuttonActionPerformed(evt);
            }
        });

        jLabel2.setText("CRM");

        jLabel3.setText("Especialidade");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel2)
                                                .addGap(18, 18, 18)
                                                .addComponent(crmText, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(jLabel3)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(especialidadeJcombobox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addComponent(jLabel1)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                .addComponent(nomeText, javax.swing.GroupLayout.PREFERRED_SIZE, 420, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addComponent(salvarJbutton)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                .addComponent(fecharJbutton)))
                                                .addGap(0, 0, Short.MAX_VALUE)))
                                .addContainerGap())
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(25, 25, 25)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel1)
                                        .addComponent(nomeText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel2)
                                        .addComponent(crmText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel3)
                                        .addComponent(especialidadeJcombobox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(salvarJbutton)
                                        .addComponent(fecharJbutton))
                                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void salvarJbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salvarJbuttonActionPerformed
        validarDados();
    }//GEN-LAST:event_salvarJbuttonActionPerformed

    private void fecharJbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fecharJbuttonActionPerformed
        dispose();
    }//GEN-LAST:event_fecharJbuttonActionPerformed

    private void validarDados() {
        String nome = nomeText.getText();
        String crm = crmText.getText();

        Especialidade especialidade = (Especialidade) especialidadeJcombobox.getSelectedItem();

        if (nome.isEmpty() || crm.isEmpty() || especialidade == null) {
            JOptionPane.showMessageDialog(null, "Todos os campos devem ser preenchidos!");
            return;
        }

        try {
            Medico medico = new Medico();
            medico.setNome(nome);
            medico.setCrm(crm);
            medico.setEspecialidade(especialidade);

            medicoDao.salvar(medico);

            JOptionPane.showMessageDialog(null, "Médico cadastrado com sucesso!");
            limparForm();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Erro ao cadastrar médico: " + e.getMessage());
        }
    }

    private void limparForm() {
        nomeText.setText("");
        crmText.setText("");
        especialidadeJcombobox.setSelectedIndex(0);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField crmText;
    private javax.swing.JComboBox<Especialidade> especialidadeJcombobox;
    private javax.swing.JButton fecharJbutton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField nomeText;
    private javax.swing.JButton salvarJbutton;
    // End of variables declaration//GEN-END:variables
}
