/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.edu.imepac.clinica.medica.especialidades;

import br.edu.imepac.clinica.medica.daos.EspecialidadeDao;
import br.edu.imepac.clinica.medica.entidades.Especialidade;
import javax.swing.JOptionPane;

/**
 *
 * @author ehf_v
 */
public class EditarEspecialidade extends javax.swing.JFrame {

    private EspecialidadeDao especialidadeDao;

    /**
     * Creates new form CadastroEspecialidade
     */
    public EditarEspecialidade(int id) {
        initComponents();
        inicializarespecialidadeDao();
        carregarDadosDeEdicao(id);
    }

    private void inicializarespecialidadeDao() {
        try {
            this.especialidadeDao = new EspecialidadeDao();
        } catch (Exception exception) {
            JOptionPane.showMessageDialog(null, "Erro ao conectar ao banco de dados!");
            dispose();
        }
    }

    private void carregarDadosDeEdicao(int id) {
        try {
            Especialidade especialidade = especialidadeDao.buscarPorId(id);
            nomeText.setText(especialidade.getNome());
        } catch (Exception exception) {
            JOptionPane.showMessageDialog(null, "Erro ao buscar dados no banco de dados!");
            dispose();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        nomeText = new javax.swing.JTextField();
        salvarEspecialidade = new javax.swing.JButton();
        fecharButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Nome");

        salvarEspecialidade.setText("Salvar");
        salvarEspecialidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salvarEspecialidadeActionPerformed(evt);
            }
        });

        fecharButton.setText("Fechar");
        fecharButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fecharButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(nomeText, javax.swing.GroupLayout.PREFERRED_SIZE, 420, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(salvarEspecialidade)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(fecharButton)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(nomeText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(salvarEspecialidade)
                    .addComponent(fecharButton))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void fecharButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fecharButtonActionPerformed
        dispose();
    }//GEN-LAST:event_fecharButtonActionPerformed

    private void salvarEspecialidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salvarEspecialidadeActionPerformed
        boolean isValid = validarDadosObrigatorios();
        if (isValid == true) {
            Especialidade especialidade = new Especialidade();
            especialidade.setNome(nomeText.getText());

            try {
                EspecialidadeDao especialidadeDao = new EspecialidadeDao();
                especialidadeDao.atualizar(especialidade);
            } catch (Exception exception) {
                JOptionPane.showMessageDialog(
                        this,
                        "Banco de dados indisponível!");
            }
            JOptionPane.showMessageDialog(
                    this,
                    "Especialidade atualizada com sucesso!");
            limparForm();
        }
    }//GEN-LAST:event_salvarEspecialidadeActionPerformed

    private boolean validarDadosObrigatorios() {
        if (nomeText.getText().isBlank()) {
            JOptionPane.showMessageDialog(
                    this,
                    "O campo nome é obrigatório!"
            );
            return false;
        }
        return true;
    }

    private void limparForm() {
        nomeText.setText("");
        nomeText.requestFocusInWindow();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton fecharButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField nomeText;
    private javax.swing.JButton salvarEspecialidade;
    // End of variables declaration//GEN-END:variables
}
